const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
let saved=null,writes=0,fail=false;
const context=vm.createContext({console,crypto:require('node:crypto').webcrypto,structuredClone,TextEncoder,
 localStorage:{getItem:()=>saved,setItem:(key,value)=>{if(fail)throw new Error('quota');saved=value;writes++}}});
for(const file of ['storage','tasks','projects','sources','protocols','checks','reviews','interchange'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file+'.js'),'utf8'),context);
const run=code=>vm.runInContext(code,context);let passed=0;
function test(name,code){assert.equal(run(code),true,name);passed++;console.log('PASS '+name)}
run(`var minimal={format:'my-projects',formatVersion:1,project:{name:'AI checklist',tasks:[{name:'A',children:[{name:'Child'}]},{name:'B'}]}}`);
const beforeMinimalWrites=writes;
test('minimal nested AI checklist',`var first=importProjectFile(minimal);var roots=getSiblingTasks(first.id);roots.map(t=>t.name).join(',')==='A,B'&&getChildren(roots[0].id)[0].name==='Child'&&roots.every(t=>t.status==='not_started')`);
assert.equal(writes,beforeMinimalWrites+1);
run(`var original=createProject({name:'History'});var a=createTask({projectId:original.id,name:'A'});var b=createTask({projectId:original.id,name:'B'});var c=createTask({projectId:original.id,parentId:a.id,name:'Child'});var deep=createTask({projectId:original.id,parentId:c.id,name:'Deep'});setTaskCompleted(c.id,true);setTaskCompleted(a.id,false);moveTask(b.id,'up');
var source=createSource({projectId:original.id,taskId:c.id,title:'Source',description:'line1\\nline2',url:'https://example.test'});var v1=createSourceVersion({sourceId:source.id,version:'1',fileName:'test.pdf',notes:'first'});var v2=createSourceVersion({sourceId:source.id,version:'2',url:'https://example.test/v2'});createSource({projectId:original.id,title:'Project source'});
var protocol=createProtocol({name:'Protocol'});var item=createProtocolItem({protocolId:protocol.id,title:'Item'});var pv=getActiveProtocolVersion(protocol.id);var check=createCheck({taskId:c.id,sourceVersionId:v1.id,protocolId:protocol.id,protocolVersionId:pv.id});updateCheckResult({checkResultId:getCheckResults(check.id)[0].id,status:'pass'});var review=createReview({checkId:check.id,reviewer:'R'});updateReviewStatus({reviewId:review.id,status:'approved'});var newer=createProtocolVersion({protocolId:protocol.id,version:'2',copyFromVersionId:pv.id});activateProtocolVersion(newer.id);var unrelated=createProtocol({name:'Unrelated template'});var exported=exportProjectFile(original.id);var oldSnapshot=JSON.stringify(state);`);
test('single project export preserves subtree/order/status/history only',`exported.project.tasks[0].name==='B'&&exported.project.tasks[1].status==='in_progress'&&exported.project.tasks[1].children[0].status==='completed'&&exported.protocols.length===1&&exported.protocols[0].versions.length===1&&exported.protocols[0].versions[0].status==='retired'&&exported.checks[0].review.status==='approved'&&exported.project.sources[0].title==='Project source'&&exported.project.tasks[1].children[0].sources[0].versions.length===2&&!('schemaVersion' in exported)`);
const beforeHistoryWrites=writes;
test('import does not mutate any existing object',`var oldObjects=Object.fromEntries(INTERCHANGE_COLLECTIONS.map(k=>[k,JSON.stringify(state[k])]));var copy=importProjectFile(exported);INTERCHANGE_COLLECTIONS.every(k=>JSON.stringify(state[k].slice(0,JSON.parse(oldObjects[k]).length))===oldObjects[k])`);
assert.equal(writes,beforeHistoryWrites+1);
test('full export-import-export semantic roundtrip',`var again=exportProjectFile(copy.id);delete again.exportedAt;var baseline=structuredClone(exported);delete baseline.exportedAt;JSON.stringify(again)===JSON.stringify(baseline)`);
test('all IDs and references are independent',`var copyTasks=getProjectTasks(copy.id);var copyCheck=state.checks.find(ch=>copyTasks.some(t=>t.id===ch.taskId));copy.id!==original.id&&!copyTasks.some(t=>getProjectTasks(original.id).some(old=>old.id===t.id))&&copyCheck.id!==check.id&&getSourceVersion(copyCheck.sourceVersionId).id!==v1.id&&getProtocolVersion(copyCheck.protocolVersionId).id!==pv.id&&getCheckResults(copyCheck.id)[0].protocolItemId!==item.id&&getReviewForCheck(copyCheck.id).id!==review.id`);
test('same file imported twice with original present',`var third=importProjectFile(exported);third.id!==copy.id&&third.id!==original.id&&state.projects.filter(p=>p.name==='History').length===3`);
test('refresh retains reconstructed relationships',`saveState();state=loadState();var reload=exportProjectFile(copy.id);delete reload.exportedAt;JSON.stringify(reload)===JSON.stringify(baseline)`);
function reject(name,expr){test(name,`var before=JSON.stringify(state);var rejected=false;try{${expr}}catch{rejected=true}rejected&&JSON.stringify(state)===before`)}
reject('invalid JSON',`parseProjectFile('{')`);
reject('wrong format',`importProjectFile({...minimal,format:'other'})`);
reject('unknown version',`importProjectFile({...minimal,formatVersion:2})`);
reject('missing project name',`importProjectFile({format:'my-projects',formatVersion:1,project:{tasks:[]}})`);
reject('invalid array type',`importProjectFile({...minimal,project:{name:'bad',tasks:{}}})`);
reject('invalid status',`importProjectFile({...minimal,project:{name:'bad',tasks:[{name:'x',status:'done'}]}})`);
reject('duplicate references',`importProjectFile({...minimal,project:{name:'bad',tasks:[{name:'x',ref:'same'},{name:'y',ref:'same'}]}})`);
reject('unknown task reference',`var broken=structuredClone(exported);broken.checks[0].taskRef='missing';importProjectFile(broken)`);
reject('cross-task source version reference',`var broken=structuredClone(exported);broken.checks[0].taskRef=broken.project.tasks[0].ref;importProjectFile(broken)`);
reject('wrong protocol version',`var broken=structuredClone(exported);broken.checks[0].protocolVersionRef='missing';importProjectFile(broken)`);
reject('missing result item',`var broken=structuredClone(exported);broken.checks[0].results=[];importProjectFile(broken)`);
reject('duplicate result',`var broken=structuredClone(exported);broken.checks[0].results.push(structuredClone(broken.checks[0].results[0]));importProjectFile(broken)`);
reject('failed check cannot have approved review',`var broken=structuredClone(exported);broken.checks[0].status='failed';broken.checks[0].results[0].status='fail';importProjectFile(broken)`);
reject('prototype pollution key',`importProjectFile(parseProjectFile('{'+'"format":"my-projects","formatVersion":1,"project":{"name":"bad","tasks":[],"__proto__":{"polluted":true}}}'))`);
reject('excessive collection',`importProjectFile({...minimal,project:{name:'large',tasks:Array.from({length:5001},()=>({name:'t'}))}})`);
reject('excessive depth',`var node={name:'leaf'};for(var i=0;i<50;i++)node={name:'parent',children:[node]};importProjectFile({...minimal,project:{name:'deep',tasks:[node]}})`);
reject('bad date or datatype',`importProjectFile({...minimal,project:{name:'bad',tasks:[{name:12}],createdAt:'yesterday'}})`);
reject('unknown field',`importProjectFile({...minimal,project:{...minimal.project,storageKey:'danger'}})`);
const beforeFailure=run('JSON.stringify(state)'),savedBefore=saved,writesBefore=writes;fail=true;
assert.throws(()=>run('importProjectFile(minimal)'),/quota/);fail=false;
assert.equal(run('JSON.stringify(state)'),beforeFailure);assert.equal(saved,savedBefore);assert.equal(writes,writesBefore);passed++;console.log('PASS storage failure rolls back memory and storage');
test('HTML remains text',`var htmlProject=importProjectFile({...minimal,project:{name:'<img src=x>',tasks:[{name:'<script>bad()</script>'}]}});getProjectTasks(htmlProject.id)[0].name==='<script>bad()</script>'`);
reject('corrupt local project export fails without mutation',`var loadedDeep=state.tasks.find(t=>t.id===deep.id);var savedParent=loadedDeep.parentId;loadedDeep.parentId='missing';try{exportProjectFile(original.id)}finally{loadedDeep.parentId=savedParent}`);
reject('nonexistent calendar date',`importProjectFile({...minimal,project:{...minimal.project,createdAt:'2026-02-31T12:00:00Z'}})`);
reject('unsupported large file',`parseProjectFile('x'.repeat(PROJECT_FILE_LIMIT+1))`);
reject('unrelated protocol template',`var extra=structuredClone(exported);extra.protocols.push({name:'Unused',version:'1',versions:[]});importProjectFile(extra)`);
test('50 task levels accepted',`var node={name:'leaf'};for(var i=0;i<49;i++)node={name:'parent',children:[node]};var atLimit=importProjectFile({...minimal,project:{name:'50 levels',tasks:[node]}});getProjectTasks(atLimit.id).length===50&&exportProjectFile(atLimit.id).project.tasks.length===1`);
const formatDoc=fs.readFileSync(path.join(__dirname,'../docs/project-interchange-format.md'),'utf8');
context.docExamples=[...formatDoc.matchAll(/```json\n([\s\S]*?)```/g)].map(match=>JSON.parse(match[1]));
test('documented JSON examples validate',`docExamples.length===3&&docExamples.every(example=>prepareProjectImport(example).projects.length===1)`);
console.log(`Passed ${passed} interchange tests`);
